
name: "bloom-176b"
backend: "python"
max_batch_size: 32
input [
  {
    name: "INPUT__0"
    data_type: TYPE_INT32
    dims: [512]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_INT32
    dims: [ 512 ]
  }
]


dynamic_batching {
   preferred_batch_size: 16
   max_queue_delay_microseconds: 1000
 }
